const dataConfig = {
  names: [
    'Brendon Barber',
    'Juliana Henderson',
    'Graham Edwards',
    'Frances Lutz',
    'Dominique Krause',
    'Elliott Foley',
    'Pamela Garrison',
    'Gisselle Johnston',
    'Jadyn Bullock',
    'Ximena Ewing',
    'Bianca Horn',
    'Liam Castaneda'
  ],
  companies: [
    'Ciklum',
    'Ubisoft',
    'PMLAB',
    'DevCom',
    'UKEESS Software House',
    'SoftServe',
    'Sigma Software',
    'Luxoft',
    'Astound Commerce',
    'SSA Group',
    'ELEKS',
    'DataArt',
    'Svitla Systems, Inc.',
    'Levi9 Ukraine',
    'Infopulse',
    'Lohika',
    'Intellias',
    'EPAM',
    'N-iX',
    'GlobalLogic',
    'PLVision',
    'Grammarly'
  ],
  positions: [
    'Computer Scientist',
    'IT Professional',
    'UX Designer & UI Developer',
    'SQL Developer',
    'Web Designer',
    'Web Developer',
    'Help Desk Worker/Desktop Support',
    'Software Engineer',
    'Data Entry',
    'DevOps Engineer',
    'Computer Programmer',
    'Network Administrator',
    'Information Security Analyst',
    'Artificial Intelligence Engineer',
    'Cloud Architect',
    'IT Manager',
    'Technical Specialist',
    'Application Developer',
    'Chief Technology Officer (CTO)',
    'Chief Information Officer (CIO)'
  ]
};

export default dataConfig;